### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HelloWorldNoSegfault**

### CODE REVIEW

**Comment by HelloWorldNoSegfault** [comment]
LOL this is interesting

**Comment by HelloWorldNoSegfault** [comment]
nOthING woRKs aNd I DoN't kNoW WHy

**Comment by HelloWorldNoSegfault** [comment]
LGTM

**Comment by HelloWorldNoSegfault** [comment]
Good job

**Comment by HelloWorldNoSegfault** [comment]
LGTM

**Comment by IPshare** [comment]
LOL Good code

**Comment by IPshare** [comment]
Code snippet:
```python
i = 100
j = 1000
k = 10000
for t in range(i):
    print('YouR ToILet BloWed UP')
```

**Comment by IPshare** [comment]
- A
- B
- C

**Comment by IPshare** [comment]
1. A
2. B
3. C

**Comment by HelloWorldNoSegfault** [comment]
Good work

**Comment by IPshare** [comment]
Another code snippet:
```
i = 100
j = 1000
k = 10000
for t in range(i):
    print('YouR ToILet BloWed UP')
```

**Comment by HelloWorldNoSegfault** [comment]
Shit code

**Comment by HelloWorldNoSegfault** [comment]
LGTM

**Comment by HelloWorldNoSegfault** [comment]
Test Test Test

**Comment by HelloWorldNoSegfault** [comment]
Markdown:
```
print('lol')
```

**Comment by HelloWorldNoSegfault** [comment]
LGTM

**Comment by HelloWorldNoSegfault** [comment]
markdown
```
test = 1
```

**Pull request merged**
